"""Export a trained policy MLP checkpoint to a C source file that nn_policy.c
can compile in. Run after training to refresh libcomputer/weights_policy.c.

    uv run python -m othello_ml.scripts.dump_weights <experiment_dir>

Picks up the latest checkpoint from <experiment_dir>/checkpoints/LATEST.
"""

import os
import sys

import toml
import torch


def fmt_float(v):
    # %g drops the decimal point for integral values, so "-0.0" -> "-0", and
    # appending "f" yields "-0f" which C parses as an invalid octal literal.
    # Force a decimal in those cases.
    s = f'{v:.9g}'
    if '.' not in s and 'e' not in s and 'n' not in s and 'i' not in s:
        s += '.0'
    return s + 'f'


def emit_float_array(name, tensor, file):
    """Write a 1D float array as a C static const array, ~8 values per line."""
    flat = tensor.detach().cpu().contiguous().view(-1).tolist()
    file.write(f'static const float {name}[{len(flat)}] = {{\n')
    for i in range(0, len(flat), 8):
        chunk = flat[i:i + 8]
        file.write('  ' + ', '.join(fmt_float(v) for v in chunk) + ',\n')
    file.write('};\n\n')


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <experiment_dir>", file=sys.stderr)
        sys.exit(1)

    experiment_dir = sys.argv[1].rstrip('/')

    config_path = os.path.join(experiment_dir, 'config.toml')
    with open(config_path) as f:
        config = toml.load(f)

    settings = config['settings']
    model_name = settings['model_name']
    if model_name not in ('NN', 'NN_single', 'NN_no_valid'):
        print(
            f"[dump_weights] skipping: model_name={model_name!r} not yet supported "
            f"by the C inference path; nothing to dump",
            file=sys.stderr,
        )
        return

    params = settings['model_params']
    input_shape = params['input_shape']
    N1 = params['N1']
    has_l2 = model_name in ('NN', 'NN_no_valid')
    N2 = params['N2'] if has_l2 else None
    # L1 input size: NN_no_valid drops the leading 64-byte valid plane, so L1
    # is 64 narrower than the formatted-input width. C inference slices the
    # same prefix off before the first matmul.
    l1_input = (input_shape - 64) if model_name == 'NN_no_valid' else input_shape

    latest_path = os.path.join(experiment_dir, 'checkpoints', 'LATEST')
    if os.path.exists(latest_path):
        with open(latest_path) as f:
            ckpt_path = f.read().strip()
    else:
        # Modal runs may ship only best.pt without LATEST.
        ckpt_path = os.path.join(experiment_dir, 'checkpoints', 'best.pt')
    print(f"loading checkpoint {ckpt_path}", file=sys.stderr)

    cp = torch.load(ckpt_path, weights_only=False, map_location='cpu')
    state = cp['model_state_dict']
    epoch = cp.get('epoch', -1)

    # torch.compile wraps the module in OptimizedModule and prefixes all state
    # keys with "_orig_mod."; strip it transparently so checkpoints from
    # compiled and uncompiled runs both load.
    if any(k.startswith('_orig_mod.') for k in state):
        state = {k[len('_orig_mod.'):]: v for k, v in state.items()}

    # Shapes from train.py's NN class:
    #   l1: Linear(input_shape -> N1)
    #   l2: Linear(N1 -> N2)
    #   l3: Linear(N2 -> 64)
    # PyTorch stores Linear weights as (out_features, in_features) row-major,
    # which matches the row_major_idx(out, in, n_in) layout in nn.c.
    if has_l2:
        expected = {
            'l1.weight': (N1, l1_input),
            'l1.bias': (N1,),
            'l2.weight': (N2, N1),
            'l2.bias': (N2,),
            'l3.weight': (64, N2),
            'l3.bias': (64,),
        }
    else:
        # NN_single: input -> N1 -> 64 (no middle layer).
        expected = {
            'l1.weight': (N1, l1_input),
            'l1.bias': (N1,),
            'l3.weight': (64, N1),
            'l3.bias': (64,),
        }
    for k, want in expected.items():
        got = tuple(state[k].shape)
        if got != want:
            print(f"shape mismatch: {k} expected {want} got {got}", file=sys.stderr)
            sys.exit(1)

    # __file__ lives at <repo>/training/othello_ml/scripts/dump_weights.py;
    # walk up four dirnames to reach the repo root.
    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
        'libcomputer', 'weights_policy.c',
    )

    with open(out_path, 'w') as f:
        f.write(f'/* Auto-generated by othello_ml/scripts/dump_weights.py\n')
        f.write(f'   Source checkpoint: {ckpt_path}\n')
        f.write(f'   Epoch: {epoch}\n')
        f.write(f'   Architecture: {model_name} (MLP), formatted_input={input_shape}, '
                f'l1_input={l1_input}, N1={N1}'
                + (f', N2={N2}' if has_l2 else '')
                + ', N_outputs=64\n')
        f.write(f'   Do not hand-edit; re-run dump_weights.py to refresh. */\n\n')

        # NN_POLICY_INPUT_SHAPE: full width emitted by nn_format_input.
        # NN_POLICY_L1_INPUT_SIZE: width L1 actually consumes (may be smaller
        # if a leading slice was dropped, e.g. NN_no_valid).
        f.write(f'#define NN_POLICY_INPUT_SHAPE {input_shape}\n')
        f.write(f'#define NN_POLICY_L1_INPUT_SIZE {l1_input}\n')
        f.write(f'#define NN_POLICY_N1 {N1}\n')
        f.write(f'#define NN_POLICY_HAS_L2 {1 if has_l2 else 0}\n')
        if has_l2:
            f.write(f'#define NN_POLICY_N2 {N2}\n')
        f.write(f'#define NN_POLICY_N_OUTPUTS 64\n\n')

        emit_float_array('nn_policy_l1_weights', state['l1.weight'], f)
        emit_float_array('nn_policy_l1_biases',  state['l1.bias'],   f)
        if has_l2:
            emit_float_array('nn_policy_l2_weights', state['l2.weight'], f)
            emit_float_array('nn_policy_l2_biases',  state['l2.bias'],   f)
        emit_float_array('nn_policy_l3_weights', state['l3.weight'], f)
        emit_float_array('nn_policy_l3_biases',  state['l3.bias'],   f)

    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == '__main__':
    main()
