#pragma once

#include <stdint.h>

typedef struct othello_game     othello_game_t;
typedef struct othello_move_ctx othello_move_ctx_t;

/* A policy-network move selector for the modern training pipeline.

   Runs the trained MLP from weights_policy.c (generated by
   othello_ml/scripts/dump_weights.py), masks invalid moves at the logit
   level, and returns the argmax move as a single-bit bitboard.

   board_lookback=0 only for now -- the input layout is exactly what
   nn_format_input(game, ctx, NULL, 0, ...) produces. */

uint64_t
nn_policy_select_move( othello_game_t const *     game,
                       othello_move_ctx_t const * ctx );
