"""Export a trained policy MLP checkpoint to a C source file that nn_policy.c
can compile in. Run after training to refresh libcomputer/weights_policy.c.

    uv run python -m othello_ml.scripts.dump_weights <experiment_dir>

Picks up the latest checkpoint from <experiment_dir>/checkpoints/LATEST.
"""

import os
import sys

import toml
import torch


def emit_float_array(name, tensor, file):
    """Write a 1D float array as a C static const array, ~8 values per line."""
    flat = tensor.detach().cpu().contiguous().view(-1).tolist()
    file.write(f'static const float {name}[{len(flat)}] = {{\n')
    for i in range(0, len(flat), 8):
        chunk = flat[i:i + 8]
        file.write('  ' + ', '.join(f'{v:.9g}f' for v in chunk) + ',\n')
    file.write('};\n\n')


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <experiment_dir>", file=sys.stderr)
        sys.exit(1)

    experiment_dir = sys.argv[1].rstrip('/')

    config_path = os.path.join(experiment_dir, 'config.toml')
    with open(config_path) as f:
        config = toml.load(f)

    settings = config['settings']
    model_name = settings['model_name']
    if model_name != 'NN':
        print(f"only NN (MLP) supported right now, got {model_name!r}", file=sys.stderr)
        sys.exit(1)

    params = settings['model_params']
    input_shape = params['input_shape']
    N1 = params['N1']
    N2 = params['N2']

    latest_path = os.path.join(experiment_dir, 'checkpoints', 'LATEST')
    with open(latest_path) as f:
        ckpt_path = f.read().strip()
    print(f"loading checkpoint {ckpt_path}", file=sys.stderr)

    cp = torch.load(ckpt_path, weights_only=False, map_location='cpu')
    state = cp['model_state_dict']
    epoch = cp.get('epoch', -1)

    # Shapes from train.py's NN class:
    #   l1: Linear(input_shape -> N1)
    #   l2: Linear(N1 -> N2)
    #   l3: Linear(N2 -> 64)
    # PyTorch stores Linear weights as (out_features, in_features) row-major,
    # which matches the row_major_idx(out, in, n_in) layout in nn.c.
    expected = {
        'l1.weight': (N1, input_shape),
        'l1.bias': (N1,),
        'l2.weight': (N2, N1),
        'l2.bias': (N2,),
        'l3.weight': (64, N2),
        'l3.bias': (64,),
    }
    for k, want in expected.items():
        got = tuple(state[k].shape)
        if got != want:
            print(f"shape mismatch: {k} expected {want} got {got}", file=sys.stderr)
            sys.exit(1)

    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        'libcomputer', 'weights_policy.c',
    )

    with open(out_path, 'w') as f:
        f.write(f'/* Auto-generated by othello_ml/scripts/dump_weights.py\n')
        f.write(f'   Source checkpoint: {ckpt_path}\n')
        f.write(f'   Epoch: {epoch}\n')
        f.write(f'   Architecture: NN (MLP), input_shape={input_shape}, '
                f'N1={N1}, N2={N2}, N_outputs=64\n')
        f.write(f'   Do not hand-edit; re-run dump_weights.py to refresh. */\n\n')

        f.write(f'#define NN_POLICY_INPUT_SHAPE {input_shape}\n')
        f.write(f'#define NN_POLICY_N1 {N1}\n')
        f.write(f'#define NN_POLICY_N2 {N2}\n')
        f.write(f'#define NN_POLICY_N_OUTPUTS 64\n\n')

        emit_float_array('nn_policy_l1_weights', state['l1.weight'], f)
        emit_float_array('nn_policy_l1_biases',  state['l1.bias'],   f)
        emit_float_array('nn_policy_l2_weights', state['l2.weight'], f)
        emit_float_array('nn_policy_l2_biases',  state['l2.bias'],   f)
        emit_float_array('nn_policy_l3_weights', state['l3.weight'], f)
        emit_float_array('nn_policy_l3_biases',  state['l3.bias'],   f)

    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == '__main__':
    main()
